development:
  adapter: postgresql
  encoding: unicode
  database: dishoftheweek_dev
  pool: 5
  username: rails
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: dishoftheweek_test
  pool: 5
  username: rails
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: dishoftheweek_production
  pool: 5
  username: rails
  password: password